### ISSUE TITLE
Wrong subtitle highlight

### ISSUE THREAD

**Issue by y4izus** [qiskit-community/qiskit-textbook#425] opened 2020-06-03 08:18 UTC
## Describe the Issue

When going to the last block of the page, if it is small it is not highlighted on the table of contents on the right. For example:

Link to "Contributors": https://qiskit.org/textbook/preface.html#Contributors
Result: "Contact" highlighted
<img width="248" alt="Screen Shot 2020-06-03 at 10 04 23" src="https://user-images.githubusercontent.com/17231966/83611687-9d800b00-a581-11ea-9d44-4cbe3d87c80e.png">

## Expected Solution

"Contributors" highlighted

## Anything else we should know?

It only happens when the last block is not enough big and the previous block is also shown. See these examples:

- Small block ❌
<img width="1342" alt="Screen Shot 2020-06-03 at 10 11 00" src="https://user-images.githubusercontent.com/17231966/83612828-3c593700-a583-11ea-9c3d-3633b1f4e143.png">

- Big block ✅
<img width="1340" alt="Screen Shot 2020-06-03 at 10 14 14" src="https://user-images.githubusercontent.com/17231966/83612852-43804500-a583-11ea-9db5-33a660b61b01.png">

**Comment by ArenaGrenade** [comment] 2020-07-02 12:39
Yes @y4izus, this could be due to how the highlight is decided upon in java script. I found the following code segment to be responsible for the right navbar highlight. This could be found in the file: [scripts.js](https://github.com/qiskit-community/qiskit-textbook/blob/master/assets/js/scripts.js)

```javascript
content.querySelectorAll('h2, h3').forEach((header, index) => {
    // Highlight based on location from the top of the screen
    var target = header.getBoundingClientRect().top
    var pixelOffset = 300;  // Number of pixels from top to be highlighted
    var id = header.id;
    if (target < pixelOffset) {
        var query = 'ul.toc__menu a[href="#' + id + '"]';
        document.querySelectorAll('ul.toc__menu li').forEach((item) => {item.classList.remove('active')});
        document.querySelectorAll(query).forEach((item) => {item.parentElement.classList.add('active')});
    }
});
```
This essentially works on the following method: 

* First we loop through all elements on page with 'h2', 'h3' tags which is all the sub-headings and headings on the page taken together.
* Then the distance of each of these elements from the top of the page, which is displayed in the browser, is calculated and stored into `target`.
* If this distance is as less as 300px (as in variable `pixelOffset`), then the corresponding element is highlighted.

But for the case that you have described, the heading is nearly past the middle of the page. Which means its, corresponding `target` value will be greater than that of `pixelOffset` (grater than 300px). Due to this the heading highlight for Contributors is not getting triggered. While on the other hand the target value of the heading "Contact" is well within `pixelOffset`, so it stays highlighted.

One way to handle this issue is to consider the distance of the headings from the bottom of the page rendered and calculate the highlight correspondingly. This way whenever a user scrolls down, and encounters a new heading, that heading will be highlighted. This is one possible solution. But the same issue will occur the other way round. If there are two sub-headings in the page, then the bottom one will be hiighlighted.


But, @y4izus I am unable to recreate the issue on my pc. Which browser do you use? Because I don't even get a right navbar on my browser.
![image](https://user-images.githubusercontent.com/56216597/86359002-0dbba280-bc8e-11ea-92cf-2bb3470d3d30.png)

Moreover, just to point out, if there are 2 sub-headings in a page taking up nearly the same space, then is it even possible to find out which section the user is looking at? In these cases we either have to consider the heading for the top-section or the heading for the bottom-section to be highlighted. And that is what is being done here. 
I hope this clears out the issue. @frankharkins

**Comment by frankharkins** [comment] 2020-07-30 08:32
@ArenaGrenade which browser do you use please?

But yes I agree this problem does not seem to have a trivial solution. I can see the selection in [the new version of Jupyter Book](https://jupyterbook.org/intro.html#contribute-to-jupyter-book) seems to 'jump' to the final chapter when you scroll to the bottom of the page. I assume this is coded as a special case, and it still has the problem that we can never scroll to highlight "Contribute to Jupyter Book" (on my screen at least).

**Comment by ArenaGrenade** [comment] 2020-08-13 02:40
> @ArenaGrenade which browser do you use please?
> 
> But yes I agree this problem does not seem to have a trivial solution. I can see the selection in [the new version of Jupyter Book](https://jupyterbook.org/intro.html#contribute-to-jupyter-book) seems to 'jump' to the final chapter when you scroll to the bottom of the page. I assume this is coded as a special case, and it still has the problem that we can never scroll to highlight "Contribute to Jupyter Book" (on my screen at least).

I tried it on chromium as well as firefox, both showed similar results. I did not yet try it after the upgrade. More or less seems like it is essentially impossible to judge which section a user is looking at if there are more than 1 section on the page. A compromise is necessary.

**Comment by frankharkins** [comment] 2020-08-18 08:21
I'm assigning this `wontfix` and closing the issue as the problem is aesthetic only, the fix is non-trivial, and we will soon be changing platforms.

**Closed by frankharkins** 2020-08-18 08:21 UTC
Labels: UI, wontfix
