### ISSUE TITLE
Qojb problem

### ISSUE THREAD

**Issue by rawanaziz** [qiskit-community/qiskit-textbook#1043] opened 2021-04-18 14:32 UTC
when , I am  running  my code  the output :
 Passing a Qobj to Backend.run is deprecated and will be removed in a future release. Please pass in circuits or pulse schedules instead.
  job = backend.run(qobj, **backend_options, **noise_config)

what should i do may you  please help me ?

**Comment by jwoehr** [comment] 2021-04-18 16:10
@rawanaziz , Qiskit code is constantly changing. The warning you have received is describing an upcoming change. In the present release, your code has no error: this is just a warning.

The change that is coming in future releases is this: all the functions which currently take a `Qobj` argument will take instead a `QuantumCircuit` or pulse schedule.

In your code, you may not have explicitly instanced a `Qobj`. It may have happened inside some other function that was called deep inside your code. If that is the case, that caller will be fixed before the change to Qiskit is complete and that caller would break.

If you prepared a `Qobj` for `backend.run()` you can change your code now and that will make the warning go away.

**Comment by rawanaziz** [comment] 2021-04-19 15:04
thanks alot for helping me , the problem here that i am using QSVC to fit   it  by using ibmq_quito as backend  -real computer,- with simulators are working effectively .

**Comment by frankharkins** [comment] 2021-04-20 13:02
closing as duplicate of #957

**Closed by frankharkins** 2021-04-20 13:02 UTC
Labels: code bug, duplicate
