### ISSUE TITLE
Section on Quantum Information

### ISSUE THREAD

**Issue by tgag17** [qiskit-community/qiskit-textbook#763] opened 2020-09-23 17:22 UTC
**What should the reader gain from this new content?**

The reader will get to learn about the basic concepts of quantum information like pure and mixed states, density matrices, average fidelity along with different channels and correlations. The class on quantum information can also be introduced in this section.

**Where do you expect this new content to fit in with the current content?**

The section could come at the end of Chapter 2 or the beginning of Chapter 3

**What material should this new content be based on?**
The book of Nielsen and Chaung or any book on quantum information can be taken as reference

**Are you proposing to write this new content?** (y/n)
I would like to contribute to this section, if it is found relevant!

**Comment by frankharkins** [comment] 2020-09-23 20:21
I'm closing this as I believe it's a duplicate of #652. Please re-open if you disagree.

**Closed by frankharkins** 2020-09-23 20:21 UTC
Labels: New Content Suggestion

**Comment by tgag17** [comment] 2020-09-24 02:28
Really sorry for the inconvenience, Will contribute in that issue if possible. Thank you

**Comment by frankharkins** [comment] 2020-09-24 11:41
@tgag17 don't apologise!
