### ISSUE TITLE
calibrating-qubits-pulse.ipynb problems

### ISSUE THREAD

**Issue by omarcostahamido** [qiskit-community/qiskit-textbook#1026] opened 2021-04-05 20:58 UTC
**Describe the bug**
There is a problem with [this notebook](https://github.com/qiskit-community/qiskit-textbook/blob/master/content/ch-quantum-hardware/calibrating-qubits-pulse.ipynb). In section 3.1 the fit, doesn't really fit. And the discrimination clouds are on top of each other.

**To Reproduce**
open the example in quantum lab

**Version info***
For qiskit problems, please provide the output of:
```
{'qiskit-terra': '0.16.4',
 'qiskit-aer': '0.7.6',
 'qiskit-ignis': '0.5.2',
 'qiskit-ibmq-provider': '0.12.2',
 'qiskit-aqua': '0.8.2',
 'qiskit': '0.24.1'}
```
For website problems please state device / OS / browser.
Chrome

**Comment by lebinyu** [comment] 2021-04-07 23:02
The fitting problem you mentioned is probably due to the inappropriate initial parameters.
To reproduce your issue, I followed [section 3.1](https://qiskit.org/textbook/ch-quantum-hardware/calibrating-qubits-pulse.html#3.1-Calibrating-$\pi$-Pulses-using-a-Rabi-Experiment-) and got the Rabi oscillation:
![1](https://user-images.githubusercontent.com/37998880/113944649-2cdef600-9805-11eb-9efb-44afc6b97358.png)
With the initial parameter offered in the code (A, B, drive_period, phi = [3, 0.1, 0.5, 0]), I got the fitting:
![2](https://user-images.githubusercontent.com/37998880/113944849-7d565380-9805-11eb-9d66-5508403eb089.png)
, where the error is because the initial value of drive_period is too large compared with the real value.
After adjusting the initial parameters (A, B, drive_period, phi = [3, 0.1, 0.3, 0]), I got a lagit result:
![3](https://user-images.githubusercontent.com/37998880/113945032-d0300b00-9805-11eb-852f-ab345fb566fe.png)

Here I suggest updating the textbook with further descriptions about choosing initial fitting parameters.

**Comment by omarcostahamido** [comment] 2021-04-09 04:09
@lebinyu very helpful. Thank you.
Did you create a PR with your suggestion?

**Comment by lebinyu** [comment] 2021-04-09 06:17
I haven't yet, but I can pull an update soon.

**Comment by frankharkins** [comment] 2023-05-30 12:27
Thanks for your contribution. I'm closing this issue as this repository is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this issue there if it's still relevant.

**Closed by frankharkins** 2023-05-30 12:27 UTC
Labels: code bug
