### ISSUE TITLE
Wrong Code in Textbook Beta: Entangled States - The Power of Entanglement

### ISSUE THREAD

**Issue by GiantToast** [qiskit-community/qiskit-textbook#1361] opened 2022-01-17 18:52 UTC
### Describe the issue

Book Section: https://learn.qiskit.org/course/introduction/entangled-states#entangled-29-0

While working through the code presented when it first introduces entanglement for encoding messages, I was getting the wrong results when trying the following code from the textbook (multiple sections combined):

```
from qiskit import Aer, QuantumCircuit
backend = Aer.get_backend('aer_simulator')

MESSAGE = '00'

qc_alice = QuantumCircuit(2,2)

# Alice encodes the message
if MESSAGE[-1]=='1':
    qc_alice.x(0)
if MESSAGE[-2]=='1':
    qc_alice.x(1)

# then she creates entangled states
qc_alice.h(1)
qc_alice.cx(1,0)

qc_bob = QuantumCircuit(2,2)
# Bob unentangles
qc_bob.cx(0,1)
qc_bob.h(0)
# Then measures
qc_bob.measure([0,1],[0,1])

backend.run(qc_alice.compose(qc_bob)).result().get_counts()
```

This works for the "00" case, but for cases where the digits are not the same the output is flipped.
After changing the bob code to decode like this:

```
qc_bob.cx(1,0)
qc_bob.h(1)
```
It works as expected.  This makes sense to me since the gates are meant to be reversible (new to this obviously).
I triple checked I was doing things as was in the book, so I think this is a mistake.

### Describe what you expect to see

Expect to see the out from the described circuits to match the original message, but instead the output is flipped.
Expect -> Message: "01", Output: "01"
Actual -> Message: "01", Output: "10"

**Comment by frankharkins** [comment] 2022-04-20 12:09
Closing this as duplicate of https://github.com/Qiskit/platypus/issues/903

**Closed by frankharkins** 2022-04-20 12:09 UTC
Labels: content bug
