### ISSUE TITLE
Mistake in Quantum Phase Estimation Intuition

### ISSUE THREAD

**Issue by PaquitoelChocolatero** [qiskit-community/qiskit-textbook#598] opened 2020-07-24 21:47 UTC
![Screenshot_20200724_234142](https://user-images.githubusercontent.com/33132109/88437770-7d452d80-ce07-11ea-97b8-292c239f950c.png)
I believe it should be 5/8 instead of 3/8, right? As the number we are encoding is 5, 3/8 doesn't resemble the ilustration

**Comment by ivanightingale** [comment] 2020-07-24 22:05
Likely duplicate of #580

**Comment by PaquitoelChocolatero** [comment] 2020-07-24 22:08
Yes! You are completely right. Thought I checked previous issues

**Closed** 2020-07-24 22:08 UTC
Labels: content bug
