### ISSUE TITLE
Missing H gate in Quantum Fourier Transform algorithm.

### ISSUE THREAD

**Issue by CodieKev** [qiskit-community/qiskit-textbook#590] opened 2020-07-24 08:29 UTC
**Describe the issue**
Chapter 3, section 3.7 that's Quantum Fourier Transform
The first image given for QFT has an error. The last qubit does not have an H gate to end with, before the swap.
**Describe what you expect to see*

**Comment by frankharkins** [comment] 2020-07-24 10:09
Duplicate of #577

**Closed by frankharkins** 2020-07-24 10:09 UTC
Labels: duplicate
